spring:
  profiles:
    active: mysql
  batch:
    job:
      # Spring Batch가 실행될때, Program arguments로 job.name 값이 넘어오면 해당 값과 일치하는 Job만 실행하기 위한 옵션
      # job.name이 parameter로 넘어오면 해당 값을 names에 할당하고 그렇지 않은 경우 NONE을 할당한다.
      # job.name이 parameter로 전달되지 않을 경우 NONE이 할당되면서 아무런 Job도 실행하지 않는다.
      # 즉, 혹시라도 값이 없을때 모든 배치가 실행되지 않도록 막는 역할입니다.
      names: ${job.name:NONE}

logging:
  level:
    org.springframework.batch: DEBUG

--- # mysql
spring:
  config:
    activate:
      on-profile: mysql

  jpa:
    properties:
      hibernate:
        show_sql: true

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: example
      driver-class-name: com.mysql.cj.jdbc.Driver
